#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfdeb;
constexpr uint24_t FX_DATA_BYTES = 132172;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

constexpr uint24_t abutton = 0x000000;
constexpr uint24_t background = 0x000302;
constexpr uint24_t bbutton = 0x001B04;
constexpr uint24_t buckbaird = 0x001E06;
constexpr uint24_t coin = 0x002108;
constexpr uint24_t creditleft = 0x00222A;
constexpr uint24_t creditpunkbottom = 0x002E2C;
constexpr uint24_t creditpunk = 0x00342E;
constexpr uint24_t ctpaw = 0x005230;
constexpr uint24_t cursor = 0x0065B2;
constexpr uint24_t dogether = 0x006674;
constexpr uint24_t dpadlr = 0x006976;
constexpr uint24_t dpadupdown = 0x006C78;
constexpr uint24_t dpad = 0x006F7A;
constexpr uint24_t drip = 0x00733C;
constexpr uint24_t easyq = 0x0074BE;
constexpr uint24_t endtextleft = 0x0079D0;
constexpr uint24_t endtext = 0x0085D2;
constexpr uint24_t froggy = 0x009A44;
constexpr uint24_t gameoverscreen = 0x00A286;
constexpr uint24_t heart = 0x00BA88;
constexpr uint24_t helpfirst = 0x00BF0A;
constexpr uint24_t helpsecond = 0x00D70C;
constexpr uint24_t helpthird = 0x00EF0E;
constexpr uint24_t ladyidle = 0x010710;
constexpr uint24_t ladytalk = 0x010DD2;
constexpr uint24_t lowerlid = 0x014A94;
constexpr uint24_t muzak = 0x014AF6;
constexpr uint24_t punklogooutlined = 0x014F78;
constexpr uint24_t selectscreen = 0x01677A;
constexpr uint24_t smoke = 0x01737C;
constexpr uint24_t stuff = 0x019D7E;
constexpr uint24_t title = 0x019F00;
constexpr uint24_t trej = 0x01B702;
constexpr uint24_t tunnelthree = 0x01BB84;
constexpr uint24_t tunneltwo = 0x01D386;
constexpr uint24_t tunnel = 0x01EB88;
constexpr uint24_t upperlid = 0x02038A;
