#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.15 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xff4d;
constexpr uint24_t FX_DATA_BYTES = 41690;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

constexpr uint24_t abutton = 0x000000;
constexpr uint24_t background = 0x000302;
constexpr uint24_t bbutton = 0x001B04;
constexpr uint24_t buckbaird = 0x001E06;
constexpr uint24_t dogether = 0x002108;
constexpr uint24_t dpad = 0x00240A;
constexpr uint24_t drip = 0x0027CC;
constexpr uint24_t gameoverscreen = 0x00294E;
constexpr uint24_t ladyidle = 0x004150;
constexpr uint24_t ladytalk = 0x004812;
constexpr uint24_t punklogooutlined = 0x0084D4;
constexpr uint24_t stuff = 0x009CD6;
constexpr uint24_t trej = 0x009E58;
